/**
 * ════════════════════════════════════════════════════════
 * IPC Green Block — Shared Type Definitions
 * Source unique des types métier pour tous les modules TS
 * ════════════════════════════════════════════════════════
 */

// ── Roles & Accès ──────────────────────────────────────
export type UserRole =
  | 'SUPER_ADMIN'
  | 'ADMIN'
  | 'MANAGER'
  | 'FINANCE'
  | 'SALES'
  | 'HR'
  | 'PRODUCTION'
  | 'LOGISTICS'
  | 'LEGAL'
  | 'STAFF'
  | 'GUEST';

export interface UserProfile {
  uid: string;
  email: string;
  role: UserRole;
  nom?: string;
  prenom?: string;
  departement?: string;
  avatar?: string;
  active: boolean;
  createdAt: string;
  _domain?: string;
}

// ── Firestore Timestamp ─────────────────────────────────
export interface FirestoreTimestamp {
  toDate: () => Date;
  toMillis: () => number;
  seconds: number;
  nanoseconds: number;
}

export type Timestamp = FirestoreTimestamp | string | Date | null;

// ── CRM ────────────────────────────────────────────────
export type RFMSegment = 'VIP_PLATINUM' | 'VIP_GOLD' | 'ACTIF' | 'A_RISQUE' | 'INACTIF';

export interface RFMScore {
  rScore: number;       // 1-5
  fScore: number;       // 1-5
  mScore: number;       // 1-5
  total: number;        // 3-15
  segment: RFMSegment;
  segmentLabel: string;
  segmentColor: string;
  ltv: number;
  avgOrderValue: number;
  recenceJours: number;
  frequence: number;
  updatedAt: Timestamp;
}

export interface Client {
  id?: string;
  nom: string;
  email?: string;
  telephone?: string;
  entreprise?: string;
  secteur?: string;
  dateNaissance?: string;
  rfm?: RFMScore;
  tags?: string[];
  _domain?: string;
  createdAt?: Timestamp;
  _updatedAt?: string;
}

export type OpportunityStage =
  | 'Prospect'
  | 'Qualification'
  | 'Proposition'
  | 'Négociation'
  | 'Bon de Commande'
  | 'Gagné'
  | 'Perdu';

export type Priority = 'Normal' | 'Urgent' | 'Critique';

export interface Opportunity {
  id?: string;
  titre?: string;
  nom?: string;
  client?: string;
  clientId?: string;
  etape: OpportunityStage;
  montant?: number;
  probabilite?: number;
  responsable?: string;
  priorite?: Priority;
  _lastRelanceAt?: string;
  _relanceCount?: number;
  _autoRelance?: boolean;
  _updatedAt?: string;
  createdAt?: Timestamp;
}

// ── Finance ─────────────────────────────────────────────
export type InvoiceStatus =
  | 'Brouillon'
  | 'À envoyer'
  | 'Envoyée'
  | 'En cours'
  | 'Payée'
  | 'En retard'
  | 'Annulée';

export interface Invoice {
  id?: string;
  num?: string;
  client?: string;
  clientId?: string;
  montant: number;
  statut: InvoiceStatus;
  dateEmission?: string;
  dateEcheance?: string;
  contratId?: string;
  _autoGenerated?: boolean;
  _type?: string;
  _domain?: string;
  createdAt?: Timestamp;
}

// ── Inventory ───────────────────────────────────────────
export interface Product {
  id?: string;
  nom?: string;
  name?: string;
  stockActuel?: number;
  stockMinimum?: number;
  seuilAlerte?: number;
  stockCible?: number;
  prixAchat?: number;
  prixVente?: number;
  fournisseurPrincipal?: string;
  _reorderInProgress?: boolean;
  _lastReorderAt?: Timestamp;
  _domain?: string;
}

// ── Notifications ───────────────────────────────────────
export type NotificationType =
  | 'DEVIS_RELANCE'
  | 'STOCK_REORDER'
  | 'CLIENT_ANNIVERSARY'
  | 'CLIENT_INACTIF_VIP'
  | 'SYSTEM';

export type NotificationStatus = 'pending' | 'read' | 'dismissed';

export interface Notification {
  id: string;
  type: NotificationType;
  priority?: Priority;
  message: string;
  status: NotificationStatus;
  channel?: ('in_app' | 'push' | 'email')[];
  createdAt?: Timestamp;
  // Context fields
  clientId?: string;
  clientNom?: string;
  productId?: string;
  targetId?: string;
  targetRef?: string;
}

// ── KPI / Analytics ─────────────────────────────────────
export interface KPICard {
  label: string;
  value: number;
  isAmount?: boolean;
  color: string;
  tag: string;
  icon: React.ReactNode;
  sub: string;
  subColor: string;
}

export interface CashFlowForecast {
  mois: string;
  prevision: number;
  optimiste: number;
  conservateur: number;
}

export interface RFMSegmentCount {
  VIP_PLATINUM: number;
  VIP_GOLD: number;
  ACTIF: number;
  A_RISQUE: number;
  INACTIF: number;
}

// ── Store (Zustand) ─────────────────────────────────────
export interface StoreData {
  finance?: {
    invoices: Invoice[];
    vendor_bills: Invoice[];
  };
  crm?: {
    opportunities: Opportunity[];
    clients: Client[];
  };
  hr?: {
    employees: UserProfile[];
  };
  inventory?: {
    products: Product[];
  };
  workflows?: Record<string, unknown>;
  signature?: {
    requests: Array<{ statut: string }>;
  };
}

export interface IpcStore {
  currentUser: UserProfile | null;
  userRole: UserRole | null;
  data: StoreData;
  config: Record<string, unknown>;
  hasPermission: (permission: string) => boolean;
  formatCurrency: (amount: number) => string;
  navigateTo: (module: string) => void;
  deleteRecord: (collection: string, id: string) => Promise<void>;
  logAction: (action: string, context?: Record<string, unknown>) => void;
  seedDemoData: () => void;
  activities: unknown[];
  shellView?: string;
}
